
substitutions:
  device_name: "garage_sensor"
  friendly_name: "Garage Sensor"
  device_description: "Logs humidty and temperature in the garage"
  settings_skipped_updates: "4"

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  comment: '${device_description}'

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret garage_api_encryption_key

# OTA Updates Password 
ota:

web_server:
  port: 80
  auth:
    username: !secret garage_web_server_username
    password: !secret garage_web_server_password
  ota: true

wifi:
  ssid: !secret garage_wifi_ssid
  password: !secret garage_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret Fallback_Wifi_Password_garage

captive_portal:

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO23
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s